using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

namespace ModuNet.SourceGenerators;

[Generator]
public class CompositionRootGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {     
        var classesWithAttributes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax cds &&
                    cds.AttributeLists.Count > 0,

                transform: static (ctx, _) =>
                {
                    var classSyntax = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
                    return symbol;
                })
            .Where(static symbol => symbol is not null);

        var markedClasses = classesWithAttributes
            .Where(static symbol =>
                symbol!.GetAttributes().Any(attr =>
                    attr.AttributeClass?.ToDisplayString()
                        == "ModuNet.SourceGenerators.Essentials.Attributes.GenerateCompositionRootAttribute"));

        context.RegisterSourceOutput(markedClasses, static (ctx, symbol) =>
        {
            var source = GenerateCompositionRoot(symbol!);
            ctx.AddSource($"I{symbol!.Name}.g.cs", source);
        });
    }

    private static string GenerateCompositionRoot(INamedTypeSymbol symbol)
    {
        return
           $$"""
                using Microsoft.Extensions.DependencyInjection;
            
                // <auto-generated/>
                namespace {{symbol.ContainingNamespace.ToDisplayString()}}
                {
                    public class {{symbol.Name}}CompositionRoot
                    {
                        private static IServiceProvider? _serviceProvider;

                        internal static void SetProvider(IServiceProvider provider)
                        {
                            ArgumentNullException.ThrowIfNull(provider);
                            _serviceProvider = provider;
                        }

                        public static IServiceScope CreateScope()
                        {
                            if (_serviceProvider == null)
                            {
                                throw new NotImplementedException("Service provider has not been initialized");
                            }

                            return _serviceProvider.CreateScope();
                        }
                    }
                }
            """;
    }
}