name: publish to nuget

on:
  push:
    branches:
      - '**'

jobs:
  publish-core:
    name: Publish ModuNet.Core
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.x

      - name: publish ModuNet.Core to NuGet
        if: github.ref == 'refs/heads/main'
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/ModuNet.Core/ModuNet.Core.csproj
          PACKAGE_NAME: ModuNet.Core
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org

  publish-aspnet-core:
    name: Publish ModuNet.AspNet.Core
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.x

      - name: publish ModuNet.AspNet.Core to NuGet
        if: github.ref == 'refs/heads/main'
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/ModuNet.AspNet.Core/ModuNet.AspNet.Core.csproj
          PACKAGE_NAME: ModuNet.AspNet.Core
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org

  publish-aspnet-rest:
    name: Publish ModuNet.AspNet.Rest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.x

      - name: publish ModuNet.AspNet.Rest to NuGet
        if: github.ref == 'refs/heads/main'
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/ModuNet.AspNet.Rest/ModuNet.AspNet.Rest.csproj
          PACKAGE_NAME: ModuNet.AspNet.Rest
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org